### ISSUE TITLE
Issue on page /03-Variaveis-IO.html

### ISSUE THREAD

**Issue by dluks82** [wmonteiro-ai/python-intro-ptbr#4]
Prezado professor, apenas uma pequena sugestão de correção:

No título do operador https://wmonteiro-ai.github.io/python-intro-ptbr/03-Variaveis-IO.html#e-logico-e utilizou o caracter (e) quando imagino pretendia utilizar (and), seguinto a mesma lógica dos títulos para os operadores lógicos anteriormente explicados.

**Comment by wmonteiro-ai** [comment]
Obrigado pela sugestão! Fiz o ajuste aqui :)
